# Generated by Django 4.0.4 on 2022-05-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analista',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='analista',
            name='data_ultima_avaliacao',
            field=models.DateTimeField(null=True),
        ),
    ]
