# Generated by Django 4.0.4 on 2022-05-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_analista_options_alter_meta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='resultado',
            field=models.IntegerField(default=0),
        ),
    ]
